name: Build and Release

on:
  push:
    tags:
      - 'v*'   # 只有推带v前缀的tag才会自动release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy and rename jar to artifact
        run: |
          mkdir artifact
          cp target/*.jar artifact/ConditionalCalculator.jar

      - name: Upload Jar to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifact/ConditionalCalculator.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
